version: "3"
services:
  alpine-nginx:
    build:
      context: .
    image: augustash/alpine-nginx:2.0.0
    labels:
      - "com.augustash.description=August Ash Alpine Nginx Image"
      - "com.augustash.development-only"
    ports:
      - "8080:80"
      - "8443:443"
    environment:
      - NGINX_DH_SIZE=128
